---
logitech_zip_url: "https://download01.logi.com/web/ftp/pub/techsupport/optionsplus/logioptionsplus_installer.zip"
logitech_app_name: "logioptionsplus_installer.app"
logitech_app_name_custom: "Logitech Options+ Installer.app"
logitech_app_path: "/Applications/{{ logitech_app_name_custom }}"